### ISSUE TITLE
Must require all of 'rspec-rails', not just components of it

### ISSUE THREAD

**Issue by weedySeaDragon** [alexrothenberg/ammeter#48]
I installed ammeter to create tests for a generator I'm writing. An error was thrown by the line <code>include RSpec::Rails::FixtureSupport</code> in <code>rspec/rails/example/rails_example_group.rb</code>
It happens because I'm not using Fixtures, so <code>RSpec::Rails::FixtureSupport</code> is undefined. Thinking it was a problem by rspec-rails,  I submitted an issue with rspec/rspec-rails: rspec/rspec-rails#1407, and they pointed out that the reason this state occurs is because ammeter is requiring only selected rspec-rails components, which shouldn't be done.  (A stack trace is included in that issue.)  They can't guarantee a coherent system state if that's done; they can only guarantee a coherent system state if <code>require rspec-rails</code> is used so that **all** of rspec-rails is required.

I'd suggest that the line <code>require 'rspec/rails/adapters'</code> and <code>require 'rspec/rails/example/rails_example_group'</code> in <code>lib/ammeter/rspec/generator/example/generator_example_group.rb</code> be replaced with the single line <code>require 'rspec-rails'</code>.  The require line could go into <code>init.rb</code> instead, to ensure that any future code that might use <code>rspec-rails</code> will not cause an error.  I can do a PR easily enough if you'd like.

**Comment by alexrothenberg** [comment]
@weedySeaDragon thanks for bringing this up.  If I remember correctly the reason for the partial require was to avoid a circular dependency that caused errors when 

1. rspec-rails required ammeter to test its own generators and
2. ammeter then required rspec-rails

I would be very happy if you could go ahead and make the change and PR. We'll just have to verify that rspec-rails can still run its own tests against the updated ammeter.

**Comment by weedySeaDragon** [comment]
Just a FYI update:  Using the following, I don't get any kind of circular dependency problems when I run the rspec/rails tests:
  - ammeter/init.rb change:  + <code>require 'rspec/rails'</code>
  - master branch for all rspec/* gems ( = 3.4.0.pre)
  - ruby 2.1.5. p273 (windows x64)
  - rails 4.2.1

I'm working on testing different configurations (older versions of rspec, ruby, rails).

**Comment by alexrothenberg** [comment]
that's great news.  I don't think you need to worry about old versions of rspec but good idea to test the versions on ruby and rails supported by rspec.

Looking forward to seeing what you're doing & thanks again for taking the initiative!
