### ISSUE TITLE
Rails 6 support?

### ISSUE THREAD

**Issue by mjankowski** [alexrothenberg/ammeter#61]
Not sure if this gem is still maintained, but  FYI:

This line - https://github.com/alexrothenberg/ammeter/blob/master/lib/ammeter/rspec/generator/matchers/have_correct_syntax.rb#L33

Has an issue with Rails 6 because that method now expects two params - https://github.com/rails/rails/blob/master/actionview/lib/action_view/template/handlers.rb#L48

I believe the fix here is to provide an empty struct as first param and the source code as second, but am not familiar enough to be confident.

**Comment by voxik** [comment]
I think your analysis is correct. I put together the #62 to fix this issue.
